services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - app-static-data:/vol/web
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=app_db
      - DB_USER=app_db_user
      - DB_PASSWORD=app_db_password
      - DB_PORT=5432
    depends_on:
      - db
    restart: on-failure

  db:
    image: postgres:15.2-alpine
    ports:
      - ":5432"
    volumes:
      - app-db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=app_db
      - POSTGRES_USER=app_db_user
      - POSTGRES_PASSWORD=app_db_password

volumes:
  app-db-data:
  app-static-data:
